# Add this block to /etc/wireguard/wg1.conf for each new client
# Replace <PUBKEY> with client public key and <IP> with assigned IP (10.66.68.X/32)

[Peer]
PublicKey = <PUBKEY>
AllowedIPs = <IP>/32
PersistentKeepalive = 25
